name: CICD
# manual click (deliver) workflow whenever user needs
on:
 workflow_dispatch:
  inputs:
    environment:
     description: This is the env value where this workflow runs
     default: 'dev'
     required: true
     type: choice
     options:
       - dev
       - prod
       - stagging

jobs:
  code:
   runs-on: ubuntu-latest
   steps:
    - name: Checkout code
      run: echo "clone code from github"
      
  build:
   needs: [code]
   runs-on: ubuntu-latest
   steps:
     - name: build the code
       run: echo "Build the code"
       
  test:
   needs: [build, code]
   runs-on: ubuntu-latest
   steps:
     - name: test the code
       run: echo "test the code"
       
  deploy:
   if: inputs.environment == 'dev'
   needs: [build,code,test]
   runs-on: ubuntu-latest
   steps:
     - name: deploy the code
       run: echo "deploy the code"
